# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [2]:
import numpy as np

2) Создать нулевой вектор размера 10

In [3]:
vektor = np.zeros(10)

print(vektor)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [4]:
vektor = np.full((1, 7), 7)

print(vektor)

[[7 7 7 7 7 7 7]]


4) Создать вектор заполненный четными числами от 10 до 100

In [5]:
vektor = np.linspace(10, 100, 46)

print(vektor)

[ 10.  12.  14.  16.  18.  20.  22.  24.  26.  28.  30.  32.  34.  36.
  38.  40.  42.  44.  46.  48.  50.  52.  54.  56.  58.  60.  62.  64.
  66.  68.  70.  72.  74.  76.  78.  80.  82.  84.  86.  88.  90.  92.
  94.  96.  98. 100.]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [7]:
vektor = np.random.randint(low=0, high=100, size=10)

print(vektor)
print(vektor[::-1])

[63 74 55  9 80 50 46  4 91 30]
[30 91  4 46 50 80  9 55 74 63]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [9]:
vektor = np.arange(9).reshape(3,3)

print(vektor)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [10]:
vektor = np.eye(4, k=1)

print(vektor)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [13]:
vektor = np.full((4, 4), 7) - np.diag([6, 5, 4, 3])

print(vektor)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [17]:
matrix = np.tile(np.arange(0, 5), (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [25]:
matrix = np.random.randint(low=0, high=100, size=(10, 10))

print(matrix)

raw_means = np.mean(matrix, axis=1).astype(int).reshape(10, 1)

print(raw_means)

matrix -= raw_means

print(matrix)

[[34 31 97 52 12  8 82 35 84 54]
 [ 7 47 70 70 10  1  7 76  9 58]
 [23 14 74 36 93 23 94 27 10  7]
 [28 70  4 72 82 49 79  4 86 47]
 [64 80 86 15 96 14 78 60 36 69]
 [60 21 39 98 54 47 19 46  2 71]
 [19 85 10 88 54 60 24 93 46 26]
 [41 93 47 23 57 60 33 53 69 15]
 [79 36  4 19 87 68 43 85 27 62]
 [51 89 12 84 62 57 86 56 13 44]]
[[48]
 [35]
 [40]
 [52]
 [59]
 [45]
 [50]
 [49]
 [51]
 [55]]
[[-14 -17  49   4 -36 -40  34 -13  36   6]
 [-28  12  35  35 -25 -34 -28  41 -26  23]
 [-17 -26  34  -4  53 -17  54 -13 -30 -33]
 [-24  18 -48  20  30  -3  27 -48  34  -5]
 [  5  21  27 -44  37 -45  19   1 -23  10]
 [ 15 -24  -6  53   9   2 -26   1 -43  26]
 [-31  35 -40  38   4  10 -26  43  -4 -24]
 [ -8  44  -2 -26   8  11 -16   4  20 -34]
 [ 28 -15 -47 -32  36  17  -8  34 -24  11]
 [ -4  34 -43  29   7   2  31   1 -42 -11]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [26]:
matrix = np.random.randint(low=0, high=100, size=(10, 10))

print(matrix)

raw_means = np.median(matrix, axis=0).astype(int).reshape(1, 10)

print(raw_means)

matrix -= raw_means

print(matrix)

[[34  5 34 91 18 37 23 88 22 62]
 [23 88 41 47 13 55 55 60 78 98]
 [15 20 54 93 66 55  7 92 70 92]
 [60 93 53 41 90 78 75 60 25 31]
 [18 22 90 94 31 90 19 73 33 52]
 [26 48 93 85 86 11 78 48 79 98]
 [92  0 22 22 62  5 83 50 54 24]
 [59  4 30 73 80 27  1  1 46 10]
 [ 3  2 54 47 14 68 45 58 26 44]
 [17 38 84 96 65 48 63 55 35 94]]
[[24 21 53 79 63 51 50 59 40 57]]
[[ 10 -16 -19  12 -45 -14 -27  29 -18   5]
 [ -1  67 -12 -32 -50   4   5   1  38  41]
 [ -9  -1   1  14   3   4 -43  33  30  35]
 [ 36  72   0 -38  27  27  25   1 -15 -26]
 [ -6   1  37  15 -32  39 -31  14  -7  -5]
 [  2  27  40   6  23 -40  28 -11  39  41]
 [ 68 -21 -31 -57  -1 -46  33  -9  14 -33]
 [ 35 -17 -23  -6  17 -24 -49 -58   6 -47]
 [-21 -19   1 -32 -49  17  -5  -1 -14 -13]
 [ -7  17  31  17   2  -3  13  -4  -5  37]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [33]:
matrix = np.random.randint(low=0, high=100, size=(5, 5))

print(matrix)

raw_min = np.min(matrix, axis=0).astype(int).reshape(1, 5)
raw_max = np.max(matrix, axis=0).astype(int).reshape(1, 5)

print(raw_min)
print(raw_max)

matrix = np.vstack((matrix, raw_min))
matrix = np.vstack((matrix, raw_max))

print(matrix)

[[10 31 95 79 62]
 [34 43 43 44 52]
 [ 1  7 25 28 29]
 [28 12 88  7 61]
 [36 32 27 15 47]]
[[ 1  7 25  7 29]]
[[36 43 95 79 62]]
[[10 31 95 79 62]
 [34 43 43 44 52]
 [ 1  7 25 28 29]
 [28 12 88  7 61]
 [36 32 27 15 47]
 [ 1  7 25  7 29]
 [36 43 95 79 62]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел

In [41]:
vektor = np.linspace(1, 51, 51)

nechet_vektor = vektor[::2]
chet_vektor = vektor[1::2]

print(nechet_vektor)
print(chet_vektor)

print(vektor)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39. 41. 43. 45. 47. 49. 51.]
[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36.
 38. 40. 42. 44. 46. 48. 50.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51.]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [47]:
print((np.arange(8)[:, None] + np.arange(8)) % 2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [48]:
matrix = np.zeros((8, 8))

matrix = (np.arange(8)[:, None] + np.arange(8)) % 2

matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)